# .bash_profile for James Bernsen
# https://github.com/jamesbernsen/dotfiles
#
# Credits:
#   https://github.com/webpro/dotfiles/blob/master/runcom/.bash_profile
#   https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile

# If not running interactively, don't do anything
[ -z "$PS1" ] && return


# I like a little verbosity...
echo "Sourcing .bash_profile ..."


# Detect PLATFORM
UNAME_S="$(uname -s)"
case $UNAME_S in
  'Linux')     PLATFORM='Linux'   ;;
  CYGWIN*)     PLATFORM='Cygwin'  ;;
  'WindowsNT') PLATFORM='Windows' ;;
  'Darwin')    PLATFORM='MacOS'   ;;
  'SunOS')     PLATFORM='Solaris' ;;
  *)           PLATFORM='other'   ;;
esac
echo "Identified platform ($UNAME_S) as \"$PLATFORM\""


# Resolve DOTFILES_DIR (assuming ~/.dotfiles on distros without readlink and/or $BASH_SOURCE/$0)
READLINK=$(command -v greadlink || command -v readlink)
CURRENT_SCRIPT=$BASH_SOURCE

if [[ -n $CURRENT_SCRIPT && -x "$READLINK" ]]; then
  SCRIPT_PATH=$($READLINK -f "$CURRENT_SCRIPT")
  DOTFILES_DIR=$(dirname "$(dirname "$SCRIPT_PATH")")
elif [ -d "$HOME/.dotfiles" ]; then
  DOTFILES_DIR="$HOME/.dotfiles"
else
  echo "Unable to find dotfiles, exiting."
  return
fi


# Read cache
DOTFILES_CACHE="$DOTFILES_DIR/.cache.sh"
[ -f "$DOTFILES_CACHE" ] && . "$DOTFILES_CACHE"


# Finally we can source the dotfiles (order matters)
for DOTFILE in "$DOTFILES_DIR"/system/.{function,function_*,path,env,alias,completion,grep,prompt,nvm,rvm,custom}; do
  [ -f "$DOTFILE" ] && echo "Sourcing ${DOTFILE#$HOME/} ..." && source "$DOTFILE"
done


# Platform-specific files
plat=$(tolower $PLATFORM) # requires function from .function_text
for DOTFILE in "$DOTFILES_DIR"/system/.{env,alias,function}.${plat}; do
  [ -f "$DOTFILE" ] && echo "Sourcing ${DOTFILE#$HOME/} ..." && source "$DOTFILE"
done


# Enable color support, if available
if [ -x /usr/bin/dircolors ]; then
  DIRCOLORS_FILE="${DOTFILES_DIR}/system/.dir_colors"
  eval "$(dircolors "$DIRCOLORS_FILE")"
fi


# Hook for machine-specific extra/custom stuff (not committed to Git)
EXTRA_DIR="$DOTFILES_DIR/extra"
if [ -d "$EXTRA_DIR" ]; then
  for EXTRAFILE in "$EXTRA_DIR"/runcom/*.sh; do
    [ -f "$EXTRAFILE" ] && echo "Sourcing ${EXTRAFILE#$HOME/} ..." && source "$EXTRAFILE"
  done
fi


# Clean up
unset READLINK CURRENT_SCRIPT SCRIPT_PATH UNAME_S DOTFILE EXTRAFILE


# Export
export PLATFORM DOTFILES_DIR EXTRA_DIR

